version: '3.8'

services:
  # Client container configuration
  bot:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: "Dockerfile.${NODE_ENV}"
    #restart: unless-stopped # restart if it is stopped
    volumes:
      - ./:/bot/
      - /bot/node_modules
    